/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* Definiranje funkcij */
void Prekinitev_konfiguracija(void);
void TIM2_IRQHandler(void);
void TIM3_IRQHandler(void);
void EXTI15_10_IRQHandler(void);

/* Deklaracija spremenljivk */
int flag=0;
int flag1=0;

void Prekinitev_konfiguracija (void){
	//Konfiguracija tipke (PC13) kot vhod
	CLEAR_BIT(GPIOC->MODER,1<<27);
	CLEAR_BIT(GPIOC->MODER,1<<26);

	//Nastavitev tipke kot pull-up
	SET_BIT(GPIOC->PUPDR, 1 << 26);
	CLEAR_BIT(GPIOC->PUPDR,1<<27);

	SET_BIT(RCC->APB2ENR, 1<<14);			// Vklop sistemske ure in periferije
	CLEAR_BIT(SYSCFG->EXTICR[3],0x00F0);	// Brisanje vrenosti na portu C za EXTI13
	SET_BIT(SYSCFG->EXTICR[3],0x0020);		// Uporaba porta C za EXTI13
	SET_BIT(EXTI->IMR,1<<13); 				// Izklop interrupt mask registra za EXTI13
	SET_BIT(EXTI->RTSR,1<<13);				// Vklop rising edge trigger registra (pull-up vkljucen)
	CLEAR_BIT(EXTI->FTSR,1<<13);			// Izklop falling edge trigger registra

	NVIC_EnableIRQ(EXTI15_10_IRQn);
}

int main(void)
{
	SET_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM2EN); // Vklop ure in periferije - TIM2
	SET_BIT(RCC->APB1ENR,RCC_APB1ENR_TIM3EN); // Vklop ure in periferije - TIM3
	SET_BIT(RCC->AHB1ENR,RCC_AHB1ENR_GPIOAEN);// Vklop ure in periferije registra A

	SET_BIT(GPIOA->MODER,1<<10);//set PA5 as output

	//TIM2 - postavitev PSCA registra in ARR registra, DIER register za prekinitev
	WRITE_REG(TIM2->PSC,16000-1);
	WRITE_REG(TIM2->ARR,1000-1);
	SET_BIT(TIM2->DIER,1);//enable interrupt
	NVIC_EnableIRQ(TIM2_IRQn);
	SET_BIT(TIM2->CR1,TIM_CR1_CEN); //enable counter
	//CLEAR_BIT(TIM2->CR1,TIM_CR1_CEN); //disable counter

	//TIM3 - postavitev PSCA registra in ARR registra, DIER register za prekinitev
	WRITE_REG(TIM3->PSC,16000-1);
	WRITE_REG(TIM3->ARR,200-1);
	SET_BIT(TIM3->DIER,1);//enable interrupt
	NVIC_EnableIRQ(TIM3_IRQn);
	SET_BIT(TIM3->CR1,TIM_CR1_CEN); //enable counter
	CLEAR_BIT(TIM3->CR1,TIM_CR1_CEN); //disable counter

	//tipka
	Prekinitev_konfiguracija();
	NVIC_DisableIRQ(EXTI15_10_IRQn);// disable button
	NVIC_EnableIRQ(EXTI15_10_IRQn);// enable button interrupt



	while(1){}}

void TIM2_IRQHandler(void){ //za blinkanje led
	WRITE_REG(TIM2->SR,0); //clear status register

	//toggle PA5
	if(flag%2 == 0){GPIOA->ODR^=GPIO_ODR_ODR_5;}
}

void TIM3_IRQHandler(void){ //za debouncing
	WRITE_REG(TIM3->SR,0); //clear status register
	flag1=0;
	CLEAR_BIT(TIM3->CR1,TIM_CR1_CEN); //disable counter

}

void EXTI15_10_IRQHandler(void) {
	SET_BIT(TIM3->CR1,TIM_CR1_CEN); //enable counter
	if(flag1==0){
		WRITE_REG(TIM3->CNT,0);
		flag=flag+1;
		if(flag%2 == 0){
			SET_BIT(TIM2->CR1,TIM_CR1_CEN); //enable counter
			WRITE_REG(TIM2->CNT,0);
			SET_BIT(GPIOA->ODR,GPIO_ODR_ODR_5);
			flag=0;
		} else {
			CLEAR_BIT(GPIOA->ODR,GPIO_ODR_ODR_5);
			CLEAR_BIT(TIM2->CR1,TIM_CR1_CEN); //disable counter
		}	}
	flag1=1;
	WRITE_REG(EXTI->PR,0x2000);          // clear interrupt pending flag
}
